[google]
spreadsheet_id = "1oNplzKXEC68PclcCW_sIGflgqZ63eV5DrzRBkMMDug4"
calendar_id    = "primary"
timezone       = "America/Chicago"

[ranges]
ledger = "ledger!A:Z"
expenses = "expenses!A:Z"
doordash = "doordash!A:Z"
goals = "goals!A:Z"